upstream app_backend {
    server 127.0.0.1:8093;
    server 127.0.0.1:8094;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 200m;

    location /admin/ {
        proxy_pass http://127.0.0.1:8092/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /app/ {
        proxy_pass http://app_backend/app/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /v3/api-docs/admin {
        proxy_pass http://127.0.0.1:8092/v3/api-docs;
    }

    location /v3/api-docs/app {
        proxy_pass http://app_backend/v3/api-docs;
    }

    location /doc/admin {
        proxy_pass http://127.0.0.1:8092/doc.html;
    }

    location /doc/app {
        proxy_pass http://app_backend/doc.html;
    }

    location /minio/ {
        rewrite ^/minio/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
