server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/fitness_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 0
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/UserMapper.xml
    - classpath*:mapper/RoleMapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: rootroot
  bucket-name: lease

logging:
  pattern:
    level: "%5p [traceId:%X{traceId}]"

springdoc:
  default-flat-param-object: true
