services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-huang
    restart: unless-stopped
    command:
      - mysqld
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine3.21
    container_name: redis-container-huang
    restart: unless-stopped
    command: ["--requirepass", "${REDIS_PASSWORD:-root}"]
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio-container-huang
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-rootroot}
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq-container-huang
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-root}
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - ${RABBITMQ_AMQP_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    image: nginx:1.28.2-alpine
    container_name: nginx-container-huang
    restart: unless-stopped
    depends_on:
      - minio
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      APP_DOMAIN: ${APP_DOMAIN:-app.localhost}
      ADMIN_DOMAIN: ${ADMIN_DOMAIN:-admin.localhost}
      FILES_DOMAIN: ${FILES_DOMAIN:-files.localhost}
      HOST_APP_API_1: ${HOST_APP_API_1:-host.docker.internal:8081}
      HOST_APP_API_2: ${HOST_APP_API_2:-host.docker.internal:8082}
      HOST_ADMIN_API: ${HOST_ADMIN_API:-host.docker.internal:8080}
      HOST_MINIO_API: ${HOST_MINIO_API:-host.docker.internal:9000}
      NGINX_ENVSUBST_FILTER: APP_DOMAIN|ADMIN_DOMAIN|FILES_DOMAIN|HOST_APP_API_1|HOST_APP_API_2|HOST_ADMIN_API|HOST_MINIO_API
    ports:
      - 80:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ../frontend/dist:/usr/share/nginx/admin:ro
      - ../frontend-app/dist:/usr/share/nginx/app:ro

volumes:
  mysql_data:
    name: mysql_data
    external: true
  redis_data:
    name: redis_data
    external: true
  minio_data:
    name: minio_data
    external: true
  rabbitmq_data:
    name: rabbitmq_data
    external: true
