server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name app.localhost localhost _;

    client_max_body_size 200m;
    root /usr/share/nginx/app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /app/ {
        proxy_pass http://host.docker.internal:8081/app/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.localhost;

    client_max_body_size 200m;
    root /usr/share/nginx/admin;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /admin/ {
        proxy_pass http://host.docker.internal:8080/admin/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name files.localhost;

    client_max_body_size 200m;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        proxy_pass http://minio-container-huang:9000;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
